version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "@Password123"  # Define a senha para o usuário root
      MYSQL_DATABASE: "dbarber"            # Nome do banco de dados que será criado
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
